### PR TITLE
Added more customization options to geom_bar

### PR DESCRIPTION
**Pull request by matthijscox**
As discussed, I added more customization of bars via user input into geom_bar.
Including auto EdgeColor and auto FaceColor (or data-driven color as Pier seems to call it).

Small example script + output:

```
x=[ones(4,1);2*ones(4,1)];
y=rand(8,1);
c=x;
l=[1:4,1:4]';
xc = arrayfun(@num2str,x,'unif',0);

clear g
g=gramm('x',xc,'y',y,'color',c,'lightness',l);
g.set_names('y','','x','');
g.geom_bar('dodge',1.5,'width',1.2,'EdgeColor','auto','FaceColor','none','LineWidth',2);
figure('Position',[100 100 400 300]);
g.draw();

set([g.facet_axes_handles],'YTick',[])
set([g.facet_axes_handles],'YColor',[1 1 1])
set([g.facet_axes_handles],'LineWidth',1)
```

image

### CODE REVIEW

**Comment by piermorel** [comment]
Thanks!

About the input parser, I just see on the doc of inputParser that there is an ```unmatched``` property in the objects. Do you know any reason for not using it (I remember some changes in the class depending on matlab versions, not sure about that one).

**Comment by matthijscox** [comment]
Indeed, and you can set keepUnmatched to true, to not throw errors. I am not that familiar with the inputParser yet, but for the sake of uniformity in your toolbox I would suggest to keep using it over custom parsers. So I will update and test it with the unmatched field. But that is for after my holiday.

**Comment by matthijscox** [comment]
Pier,
I've updated the code to use the inputParser with the keepUnmatched option. It works just as well. I've also tested the passing of unmatched arguments to patch.

Here's an example with adapted FaceAlpha and LineStyle (using similar input data as above):

```
g=gramm('x',xc,'y',y,'color',c,'lightness',l);
g.set_names('y','','x','');
g.geom_bar('dodge',1.5,'width',1.2,'EdgeColor','auto','FaceColor','auto','LineWidth',1,'FaceAlpha',0.5,'LineStyle','--');
figure('Position',[100 100 400 300]);
g.draw();
```

image

**Comment by matthijscox** [comment]
P.S. I also set the LineWidth default back to 0.5, for regression purposes. But it could also be nice to set that via `draw_data.line_size`.

**Comment by piermorel** [comment]
Merged! Thanks for the help... now I have to work this kind of option-setting in the different functions ;)

**Comment by matthijscox** [comment]
Great! It's nice to help. I've already pursuaded multiple colleagues to use GRAMM, so maybe we'll find the time to make some more changes.

**Pull request merged**
