### PR TITLE
Add borders to points

### PR DESCRIPTION
**Pull request by Nicholas-Schaub**
Two parameters were added to `set_point_options`: border_width and border_color. These options allow addition of a border to be drawn around each point. An example of a plot drawn with and without point borders is shown below.

The default is no border.
If border_width is set to a value greater than 0, a black border is drawn around each point.
If border_color is set but border_width is not, then no border will be drawn.
Acceptable values for border_color are an 1x3 RGB matrix, or the Matlab color shorthand (such as 'g' or 'green').

figure_1_a_noborder

With borders:
figure_1_a

### CODE REVIEW

**Comment by Nicholas-Schaub** [comment]
Yeah, I'm not sure why that happened. I actually split these two commits so you can accept one and not the other. I can merge them if that would be easier.

I have been active. I'm in publication mode. I'm trying to match gramm's formatting to a colleagues formatting in ggplot. I think I'm done for the immediate future once these are done :)

**Comment by Nicholas-Schaub** [comment]
Oh wait...it looks like this one and the other one are merged...I didnt mean to do that. I must not have switched branches somewhere in there. I'll fix it. My apologies.

**Comment by Nicholas-Schaub** [comment]
That should make life easier. Sorry for the confusion.

**Comment by piermorel** [comment]
Hi,

The option should be made to work with other geom/stat that can use point options (jitter, summary, etc.). The best way to find out is to do a text search of functions that use draw_data.point_size and see where it can be applied.

**Comment by Nicholas-Schaub** [comment]
Hm...I'll look into this. Sorry for the delayed response.

**Comment by piermorel** [comment]
Hi @Nicholas-Schaub , with the opportunity I have to work again on gramm I'm merging your pull request. I added some functionality to have an 'auto' border color to allow for border-only points in gramm while keeping the correct colormap

**Comment by Nicholas-Schaub** [comment]
Woah, this is quite the blast from the past.

Thanks for coming back around to this.

**Pull request merged**
