### PR TITLE
Added geom_polygons

### PR DESCRIPTION
**Pull request by Nicholas-Schaub**
Added geom_polygons to draw arbitrary polygons on figures. Polygons are drawn prior to drawing data points to prevent polygons from covering up data. Example usage is included in comments of geom_polygon.m that is a modification of the gas mileage example.

### CODE REVIEW

**Comment by piermorel** [comment]
Thanks, that looks like a great addition! I'll test it and merge asap!

**Comment by Nicholas-Schaub** [comment]
No problem. You have put together a really nice package. I was playing around with R's ggplot and I don't really like R that much, so your work here was an absolute gem to find. I needed this to draw in my own data boundaries for a big data set I'm working on. The one thing I didn't really test thoroughly was the line styles.

As I continue on, I might add some more things as I have a need for them. Rather than just hack them together quickly, I'll try to put some extra time into them and send you them. Matlab really has had a need for something like this.

**Comment by piermorel** [comment]
For plotting data boundaries there is already geom_abline / geom_vline / geom_hline in gramm but shaded areas were definitely on my todo list so it's nice. The geom_xxline have the drawback that they are always plotted on top of the plot, which I want to correct somehow (I see that your polygons are always plotted below the data). It might be worth thinking about a way to make all these related methods work as similarly as possible, which seems to be already quite the case. Thanks for putting the effort in :)

**Comment by piermorel** [comment]
Oh, an idea to make thinks easier for the users: if you omit 'x' or 'y' in this geom_polygon(), it could maybe automatically fill them in to xmin/xmax or ymin/ymax.
Your example could then be only ```g.geom_polygon('y',{[5 20] [20 30] [30 50]})```

**Comment by Nicholas-Schaub** [comment]
I actually looked at how geom_hline, etc, to see how you made those and tried to based some of what I was doing with geom_polygon on those. I tried to use as many of the functions and terminology as possible.

Specifically, I wanted the shaded regions, hence the polygons. My data has a strong linear correlation, and I wanted to manually put in my own shaded boundaries to show good data vs outliers based on criteria I created (and wasn't necessarily based off of a CI).

I know some people get touchy about other people touching their code, but I do not. If there is something you would like to change, let me know and I will try to incorporate it. I also thought about setting an options to draw over or under the data. I think this can be done with just a few additional lines of code based off of the way I have written this.

**Comment by Nicholas-Schaub** [comment]
Yeah, I like that idea of omitting 'x' and 'y'. I'll take a look and see how difficult this would be.

**Comment by piermorel** [comment]
It's probably not super difficult, but the exact axes limits are not known at the time when geom_polygon is called (I'd have the same problem with calling the geom_xxline early). 

gramm does know about the data limits though, which you can access with ```obj.var_lim.minx``` ```obj.var_lim.maxx``` ```obj.var_lim.miny``` ```obj.var_lim.maxy```
As a consequence we are probably fine with overdrawing over those a bit and hoping that the stat_ functions don't change the limits too much.

Kudos for trying to keep the function gramm-like :) I'll maybe have suggestions changes on how the options are handled. Do I have access to your branch so that we can both work on it until I merge ?

**Comment by Nicholas-Schaub** [comment]
I did some rearranging and rebased my base branch with yours. You should have access to my fork.

**Comment by piermorel** [comment]
So I took a better look, functionality-wise it is quite complete and nice. I'd simplify some stuff relative to the options though:

- I find the color stuff a bit confusing. I see that it's interesting to be able to get the colors that gramm uses (that's what 'color'  and 'fill' do right?), but It's a bit confusing with the 'map' option. I'd make two simpler color options 'fill_color' and 'line_color' that do both map or indices by recognizing whether they are containing actual colors (Vector 3 of RGB) or indices (single integers). It might allow more freedom on fill vs line as well.
- There is some processing of the defaults that could be avoided by setting single default values in my_addParameter() calls, and then simply have draw_polygons() being able to apply a single value for the options to all the polygons entered with 'x' and 'y'.

If you think that's ok, I'd work on it, it's probably simpler to show what I have in mind.

**Comment by piermorel** [comment]
The color indices also seem to only work when you use all of the indices: [2 2 2] just puts the first color (i.e. same as [1 1 1]), not the second as expected. I also try to use the old-style ```set()``` way to set graphic objects properties in order to stay compatible with older Matlab versions.

**Comment by Nicholas-Schaub** [comment]
I don't have a problem if you work on it. I probably won't have a chance to take a look at it until this weekend. However, I can give you some insight into what decisions I made and why.

The basic idea I had for this was to mimic ggplots geom_polygon. I have only been using your package for about a week or so, but it seems like you are trying to mimic ggplots syntax, so I thought it was appropriate to look up the geom_polygon function:
http://docs.ggplot2.org/current/geom_polygon.html

One of the things I always found to be confusing about ggplot is that 'color' was a variable to reference what the border line colors should be, and 'fill' was a variable to reference what the fill colors should be. So, if you only have one unique value for your variable, you only get one color. I tried to mimic this by mapping unique values to colors, so [2 2 2] should only give you the first color, but [-10 5 100] should give you three different colors where -10 is the first color, 5 is the second, etc. However, now that I read your edit I think you understand this :) The goal was to allow you to map colors to variables like ggplot allows you to do.

Now that I think about this, the indexing for 'color' and 'fill' might have a problem if you pass a cell of strings to it. I'll take a look at fixing that.

**Comment by Nicholas-Schaub** [comment]
Oh, I forgot to mention that in order to separate out the different values for a variable, I use `unique`, which sorts the values in addition to returning only the unique values of your variable. So, if you set `fill=[5,-10,100]` then what you should get the 2nd polygon displaying the 1st color (since -10 is the smallest number), the 1st polygon displaying the 2nd color, and the last polygon displaying the 3rd color.

**Comment by piermorel** [comment]
Hi, I made the changes I was mentioning. I simplified the input options. There is now only 'color','line_color','alpha','line_style'. They all expand to the number of provided polygons if single values are specified. Both 'color' and 'line_color' use get_colormap() automatically when set with a column vector of integers (indices this time, no unique used). When provided with Nx3 color matrices, they use the provided color. Some additional work might needed to check/correct these inputs.

All this actually allowed me to simplify the internal code a lot. I also added an example in examples.m to show all the ways of using it.
Let me know what you think!

**Comment by Nicholas-Schaub** [comment]
I like your changes. However, the changes you have made limit the utility a little bit. The original intention of 'color' and 'fill' was to permit someone to map the line color or fill color of a polygon to a variable (like country of origin). I did this because ggplot did this. Still, I like your code because it is much simpler and allows me to do what I want to do. You also cleaned up some of the mess I made in the code, which also makes me happy :)

If it is okay with you, I may add a few other functions as I need them. Is there any kind of philosophical approach you are taking to development of this? I was trying to base what I did on ggplots original functions in R, but I'm not a fan of the verbage they use (like using 'color' to map line colors to variables and 'fill' to map fill colors to variables). I think I like your approach of making things more obvious.

**Comment by piermorel** [comment]
I see what you mean, I've taken a look at the doc for `geom_polygon()` in ggplot before making my changes. It looks like in ggplot, `geom_polygon()` is actually for plotting data (in a weird way because you need to give the polygon coordinates). 

In contrast, I see gramm's `geom_polygon()` more as an annotation/decoration tool, as it doesn't use the actual 'x', 'y' and 'color' plotting data, which in gramm – a **major** difference with ggplot – are given exclusively in the constructor or in `update()`. In that manner, it's like geom_abline/_hline/etc., but **not** like geom_point/_line/etc. As a consequence of this, the colors from geom_polygon() were never going to end up in the legend for example. Still, I liked the ability to generate colors automatically, so I left it there. 

Now making a `geom_polygon()` that uses the actual data like in ggplot would also be a possibility, but it strikes me as something that is more complicated than it is useful. I should make more apparent in the documentation which geom_ are annotation and which are data-based.

On the gramm/ggplot, I don't actively try to keep functionality/naming between gramm/ggplot, but rather try to make things simple (for me and the user) and (hopefully) logical.

**Comment by Nicholas-Schaub** [comment]
I see it more of a decoration tool as well. I like the simple/logical approach, which I find lacking at times in ggplot. I also like your comment about annotating which geoms are for decoration vs data. I'll keep this stuff in mind if I find something else to contribute.

**Comment by Nicholas-Schaub** [comment]
Oops, I forgot we still wanted to take a look at expanding the polygons to the x and y limits if either x or y is not included.

**Comment by piermorel** [comment]
Oh true, I changed geom_abline, etc. (for now only locally) in order for it to work more similarly to geom_polygon(). This will come with an additional 'extent' option which basically says how much further the lines go compared to the data limits (default is 2). I'll probably merge the current changes soon and implement that later.

**Comment by piermorel** [comment]
Implemented! Let me know if that works for you (I modified the examples.m as well). I'll merge if all OK.

**Comment by piermorel** [comment]
Any feedback?

**Comment by Nicholas-Schaub** [comment]
I apologize. I haven't had a chance to take a look at it or test it. I can take a look at it sometime this week. I don't want to hold you up, so if you want to merge I can provide feedback afterwards.

**Comment by Nicholas-Schaub** [comment]
Looks gorgeous. Thanks for putting the finishing touches on this!

**Comment by piermorel** [comment]
Ooops, sorry for the weird activity. I'll close this once the merging done.

**Pull request merged**
