### PR TITLE
Set linewidth for fill_abline functions

### PR DESCRIPTION
**Pull request by Nicholas-Schaub**
Methods that use `fill_abline` were unable to set the line width since `set_line_options` does not interact with any `fill_abline` settings. This commit made changes to `geom_abline`, `geom_hline`, and `geom_vline` so that the line width can now be set when 'linewidth' name/value pair is used in the method.

This change required additional changes to the following files:
1. A change to `gramm` to include linewidth in the abline struct
2. A change to `fill_abline` to accept linewidth name/value pair
3. A change to `draw` to pass the 'LineWidth' name/value pair to the plotting function

It's just a minor change, but I had a need for this so I thought I'd share in case others found it useful.

### CODE REVIEW

**Comment by piermorel** [comment]
Thanks for the pull request. I think it's good if fill_abline has an independent line width setting from set_line_options(). Ultimately I want to find a way to pass any matlab parameter like what stat_ellipse does. I try to use underscores in parameter names in general, would you be ok to change 'linewidth' with 'line_width' ?

**Comment by Nicholas-Schaub** [comment]
I have no issues with that. I think I just tried to match the naming convention of the private functions. I prefer underscores.

I also think it's good to have it separate from set_line_options. The more I think about it the more I think it would be problematic. I'll make the change and commit later today.

**Comment by Nicholas-Schaub** [comment]
For whatever reason, when I made the commit to change linewidth to line_width, it is trying to change all of the files. I made several attempts to fix this, but couldn't figure out why this was happening. I reset the branch to the original pull request since I think the changes are easiest to read.

**Comment by piermorel** [comment]
Sorry it took me a while to get to it, busy times! I fixed a few things (functions are supposed to work if you create several lines) and merged.

**Pull request merged**
