### PR TITLE
Added functionality to export the created plots to a preferred filetype

### PR DESCRIPTION
**Pull request by JaapNieland**
Hi!

After one week of using gramm already a big fan. However, I missed an easy way to store the figures created. Especially for file type PDF as it requires some fiddling with the 'Papersize'. 

I hope you find it useful and as this is my first pull request ever, feel free to let me know if there is any room for improvement. 

Regards, 
Jaap Nieland

### CODE REVIEW

**Comment by piermorel** [comment]
Hi Jaap,

Thank you very much for the pull request, export is indeed something that is missing from gramm!
As a remark though, I see you are using the "handle graphics" way of setting figure properties... I try to keep doing it the set() way so that gramm stays compatible with pre 2015b versions.

Have you checked things about transparency of areas and proper vector output when using the painters renderer? This is quite a mess which depends on Matlab versions and I'm not 100% sure on how it works. There was recently an issue related to that: https://github.com/piermorel/gramm/issues/18

**Comment by JaapNieland** [comment]
Hi Pierre,

Thanks for the quick response. I've adjusted the handling of handles to use the set() function.

As for the transparency issue. This is indeed something that comes up when exporting to eps. The pdf files are fine, but the eps files are weird. 

[eps example.pdf](https://github.com/piermorel/gramm/files/639631/eps.example.pdf)
[pdf example.pdf](https://github.com/piermorel/gramm/files/639633/0.pdf)

However I use the opengl renderer for the eps export it is ok. 

[opengl eps.pdf](https://github.com/piermorel/gramm/files/639647/opengl.eps.pdf)

This is however against Mathworks [recommandations](https://nl.mathworks.com/help/matlab/ref/print.html#input_argument_renderer).

The eps files have a weird size now as I had to export them to pdf. The original eps files follow the input size.

**Comment by piermorel** [comment]
Thanks for the set() corrections. As for eps/pdf, I actually use svg now most of the time, it works quite well.

I've just tested the function, which seems to work as advertised, but I find that the default options for size don't work so well for me (I tried it on the first example in examples.m). I think that the default output (when no width or height is set) should look exactly like what is on screen (gramm does a lot under the hood so that it looks nice!). Finding the correct size in cm is also not super straightforward (for the same figure, it looks right if it's 24x12 cm, which is quite large. Do you know if Matlab's dpi option weird by default ?

**Comment by JaapNieland** [comment]
Matlab's dpi settings are apparently just a bit less random than a dice. [See here](https://nl.mathworks.com/help/matlab/creating_guis/dpi-aware-behavior-in-matlab.html)

The script now extracts the users resolution and creates measures using that as default. The resolution is in ppi though (of course) so I changed all measures to inches. I can add tomorrow an extra parameter for the preferred units, but first I hope that this works for you as well.

**Comment by JaapNieland** [comment]
I've added a parameter to use centimeters as input units. The default with and/or height are recalculated. What I also noticed, which I found to be a nice bonus coming from the previous commit, is that if you draw a figure, then resize it manually and than save it, the resized shape is used. 
I also ran the script on all plots from the examples.m file and I did not notice anything odd. This is however on a fully updated osx machine with Matlab 2016b. Unfortunately I don't have anything else to test on.

**Comment by piermorel** [comment]
Thanks for the changes, I'm checking things out... busy days. Do I have the rights to modify your branch if I want to commit some changes there before doing the pull ?

**Comment by JaapNieland** [comment]
Sure thing. I'm happy to help on this project. Adjust whatever you like. I'd like it if it is still recognisable in the history of the project that I contributed, but apart from that feel free to do as you please.

**Comment by yzliao** [comment]
I have the same issue for eps export before. One way to find it is `print -epsc2 -loose xxx.eps`. The flag `-loose` fixes the issue.

**Comment by JaapNieland** [comment]
Hi @yzliao, 

That works as wel indeed. However you are using the deprecated "Postscript level 2" instead of the newer "Postscript 3". In fact the `-loose` flag does not even matter for "Postscript level 2". Furthermore if I enforce the preferred`-painters` renderer, it stops working so I suspect that Matlab uses the `-opengl` renderer. Therefore I would prefer the current method.

**Comment by piermorel** [comment]
Hi @JaapNieland

Sorry I let the pull request on hold for quite a while. I'm looking into it right now, it seems to work as advertised. I'd like to make a changes to the default options before merging though (already done on my side):

- the default units should be in centimeters (because we are scientists... and because I'm French :) )
- I'm thinking about switching the default output to svg instead of pdf. Granted it is less common, but by experience I find that it works a bit better than pdf for further vector editing.

Any strong opinions on either of those?

I saw that in your separate commit, you changed to the 'tex' option for text. in parallel I'll push a change soon in the main branch which allows the user to set that by using set_text_options('interpreter','tex').

**Comment by piermorel** [comment]
Ultimately though it's very hard to get something proper when entering 'width' and 'height': when the default size is used (which works very well, nice!), the actual size is much bigger than the on-screen size (not surprising I guess, as our screens have higher ppi than what Matlab assumes).

**Comment by JaapNieland** [comment]
Hi @piermorel 

Both options sound good to me. Regarding measurements, I'm always in favour of SI units and since meters provide us with a horrible scale length, centimeters seems the way to go. 

Regarding pdf/svg/eps/... My only concern would be eps since the output seems a bit hacky. I'm using pdf as it seemed easier when including them in a LaTeX report, but there is probably something out there that works with svg's as well. So I'm pretty neutral and think svg is the way to go if you prefer it. 

For the size, I think this is as good as it gets. The relative sizes are appropriate and as you suggested, the output is a fine copy of the image as Matlab shows. 

I'm looking forward to the `set_text_options()` function. The way my branch handles it, is a hardcoded change which is a lot less elegant than a function.

If there is anything that needs to be changed, please let me know. I'm happy to help!

**Comment by JaapNieland** [comment]
The choices are not well thought through per se. Thing is, I'm using an external editor which has syntax highlighting, but in `gg.save()` for example will still have `save()` highlighted. `gg.export()` doesn't have this problem and might indeed be a clearer choice. 

Same holds for `path` the other choices I'm neutral.

**Comment by piermorel** [comment]
Allright, renamed to `export()` and the option to `'export_path'` ... and merged (finally)

**Pull request merged**
